stages:
  - format
  - plan
  - apply
  - destroy
  - publish

variables:
  AWS_ROLE_NAME: gitlab_runner
  AWS_ACCOUNT_ID: 471871437096
  AWS_PROFILE_NAME: cmdlabtf-master
  AWS_REGION: ap-southeast-2

format:
  stage: format
  tags:
    - cmd
  script:
    - make formatCheck

plan:
  stage: plan
  tags:
    - cmd
  script:
    - echo "pass"

apply:
  stage: apply
  tags:
    - cmd
  script:
    - echo "pass"

destroy:
  stage: destroy
  tags:
    - cmd
  script:
    - echo "pass"

publish:
  stage: publish
  tags:
    - cmd
  script:
    - make publish
  variables:
    GIT_STRATEGY: clone
  only:
    - master
    - tags
